### ISSUE TITLE
ERROR: cannot get play info, server message: "Invalid appkey parameter."

### ISSUE THREAD

**Issue by linmingjian** [kamikat/bilibili-get#18]
> bilibili-get https://www.bilibili.com/video/av42878363
extracting video metadata...
[1/1] av42878363: start download "网上那些真实的沙雕图片（第六十五期） CleanBandit-Solo"...
ERROR: cannot get play info, server message: "Invalid appkey parameter."

**Comment by catright** [comment]
This is my temporal solution to download videos only, may not work for bangumi. Thanks to youtube-dl. lol.

Change 
```
var url = yield playUrl(cid, { quality, season_type });
```
 in function `fetchPlayInfo` in extractor.js to 
```
var payload = `appkey=iVGUTjsxvpLeuDCf&cid=${cid}&otype=json&qn=${quality}&quality=${quality}&type=`;
var sign = require('crypto').createHash('md5').update(payload+'aHRmhWMLkdeMuILqORnYZocwMBpMEOdt').digest('hex');
var url = `https://interface.bilibili.com/v2/playurl?${payload}&sign=${sign}`;
```

or please wait until bilibili-playurl would be updated for new appkey.

This solution may not work if you don't have crypto module. But i guess this module is defaultly installed with node.js.

**Comment by AvrilL161** [comment]
> This is my temporal solution to download videos only, may not work for bangumi. Thanks to youtube-dl. lol.
> 
> Change
> 
> ```
> var url = yield playUrl(cid, { quality, season_type });
> ```
> in function `fetchPlayInfo` in extractor.js to
> 
> ```
> var payload = `appkey=iVGUTjsxvpLeuDCf&cid=${cid}&otype=json&qn=${quality}&quality=${quality}&type=`;
> var sign = require('crypto').createHash('md5').update(payload+'aHRmhWMLkdeMuILqORnYZocwMBpMEOdt').digest('hex');
> var url = `https://interface.bilibili.com/v2/playurl?${payload}&sign=${sign}`;
> ```
> or please wait until bilibili-playurl would be updated for new appkey.
> 
> This solution may not work if you don't have crypto module. But i guess this module is defaultly installed with node.js.

Thanks bro!!!
It's working!!!

**Comment by jovi-wang** [comment]
> > This is my temporal solution to download videos only, may not work for bangumi. Thanks to youtube-dl. lol.
> > Change
> > ```
> > var url = yield playUrl(cid, { quality, season_type });
> > ```
> > in function `fetchPlayInfo` in extractor.js to
> > ```
> > var payload = `appkey=iVGUTjsxvpLeuDCf&cid=${cid}&otype=json&qn=${quality}&quality=${quality}&type=`;
> > var sign = require('crypto').createHash('md5').update(payload+'aHRmhWMLkdeMuILqORnYZocwMBpMEOdt').digest('hex');
> > var url = `https://interface.bilibili.com/v2/playurl?${payload}&sign=${sign}`;
> > ```
> > or please wait until bilibili-playurl would be updated for new appkey.
> > This solution may not work if you don't have crypto module. But i guess this module is defaultly installed with node.js.
> 
> Thanks bro!!!
> It's working!!!

Hey mate,

Good to hear you can get it work again.

Can i ask do you need to rebuild to run command line, after you change the code?

Thanks

**Comment by liseen315** [comment]
how to get appkey and "aHRmhWMLkdeMuILqORnYZocwMBpMEOdt" token?

**Comment by jialanxin** [comment]
This Error appears again on May 2 2019.  Is "bilibili-playurl" outdated?

**Comment by nehuenpereyra** [comment]
The error has returned:
<img src="https://i.ibb.co/vvWgpYm/00.png" style="width:500px;height:600px;">

**Comment by kamikat** [comment]
bilibili have switched most of its video play service to DASH streaming. DASH play is supported by latest release of bilibili-playurl while there's some extra work to merge a dash stream with bilibili-get.

**Comment by ElegantLin** [comment]
So is there any method to fix this problem?

**Comment by kmahyyg** [comment]
Get the same error, please reopen this issue to let us get tracked.

**Comment by kamikat** [comment]
Opened #20 for DASH support.
