### ISSUE TITLE
error downloading

### ISSUE THREAD

**Issue by tinyko** [kamikat/bilibili-get#19]
`$ bilibili-get https://www.bilibili.com/video/av38063989`
`02/24 10:38:20 [ERROR] CUID#8 - Download aborted. URI=http://cn-zjwz3-dx-v-05.acgvideo.com/upgcxcode/64/85/66908564/66908564-1-80.flv?expires=1550982900&platform=pc&ssig=NqxsxcynCEFf-86UgsxocQ&oi=1035461785&trid=674d7e50b1494eb78844b6bd71c48766&nfb=maPYqpoel5MI3qOUX6YpRA==&nfc=1`
`Exception: [SocketCore.cc:874] errorCode=1 接收数据失败，原因：连接被对方重设`

**Comment by kamikat** [comment]
Cannot reproduce this problem with aria2 1.32.0. Check your network configuration maybe.

**Comment by tinyko** [comment]
$ pacman -Qi aria2   
名字           : aria2
版本           : 1.34.0-2
描述           : Download utility that supports HTTP(S), FTP, BitTorrent, and Metalink
架构           : x86_64
URL            : http://aria2.sourceforge.net/
软件许可       : GPL
组             : 无
提供           : 无
依赖于         : gnutls  libxml2  sqlite  c-ares  ca-certificates  libssh2
可选依赖       : 无
依赖它         : 无
被可选依赖     : 无
与它冲突       : 无
取代           : 无
安装后大小     : 5.55 MiB
打包者         : Felix Yan <felixonmars@archlinux.org>
编译日期       : 2019年02月08日 星期五 17时32分06秒
安装日期       : 2019年02月23日 星期六 23时13分07秒
安装原因       : 单独指定安装
安装脚本       : 否
验证者         : 数字签名

With aria2 1.34.0-2 its still the same problem whether I changed to another PC or not.
Some videos can be downloaded,but some can't.
I believe some operation may be banned by the server.
BTW thx for your work.
