### ISSUE TITLE
Feature request: request through a socks proxy

### ISSUE THREAD

**Issue by nicholascw** [kamikat/bilibili-get#2]
Wondering if it's possible to fetch  the download links with a socks proxy, and download it directly, for bypassing the limitation on copyright videos.

**Comment by kamikat** [comment]
Here's a possible solution: 

- Convert SOCKS proxy to HTTP proxy with [polipo](https://www.irif.fr/~jch//software/polipo/) (or its [docker](https://hub.docker.com/r/vimagick/polipo/) image)
- Set `HTTP_PROXY` and `HTTPS_PROXY` variable
- Run bilibili-get with `-O no-proxy=.acgvideo.com` command-line option to download video directly from video server

**Comment by kamikat** [comment]
FYI  8c0861c
