### ISSUE TITLE
lib/download.js 建議可以增加相容 windows 的用法

### ISSUE THREAD

**Issue by shadowjohn** [kamikat/bilibili-get#5]
subprocess.spawnSync 看要不要改用簡單的來達成
child_process.execSync(downloadCommand);        
或是可以有其他追蹤 download progress 的方法

**Comment by kamikat** [comment]
目前是只显示 aria2 的 progress bar，改成 execSync 虽说不会产生太大影响，但是要考虑命令行的字符转义。

方便的话，可以贴一下 windows 里面的运行日志么？

**Comment by catright** [comment]
actually, ```spawnSync(`sh`)``` is not working on my windows system.
and `execSync` is reporting an error - cannot destructure - on each aria2c run in a loop.
so i've changed ```spawnSync(`sh`, [`-c`, options], { stdio: 'inherit' })``` to ```spawnSync(`aria2c`, aria2cOptions, { stdio: 'inherit', shell: true })```. and included 'url' into `aria2cOptions`.

similarly, i've changed ```spawnSync(`sh`)``` to ```spawnSync(`ffmpeg`)``` on merging part too.

**Comment by kamikat** [comment]
@catright Thanks for help. Would you mind opening a PR on this?

**Comment by kamikat** [comment]
#14 FYI.
