### ISSUE TITLE
ERROR: cannot extract part info.

### ISSUE THREAD

**Issue by brendangl** [kamikat/bilibili-get#6]
Hi, bilibili-get was working just fine for me the other day but now I get the following with each link I try (and with links that worked previously):

extracting video metadata...
ERROR: cannot extract part info.

Is this affecting anyone else?

**Comment by catright** [comment]
i've changed

`var i = /<option[^>]*cid='(\d+)[^>]*>(\d+)、([^<]*)/g, match;`

to 

`var i = /"cid":(\d+).+?"page":(\d+).+?"part":"([^",]+)[",]/g, match;`

on a function `findVideoInfo` in _extractor.js_
and it works fine for me.

i think bilibili has changed the formatting for their video information.

**Comment by kamikat** [comment]
It seems that bilibili is migrating its video page to Vuejs.
