### ISSUE TITLE
Doesn't work for me.

### ISSUE THREAD

**Issue by arnauldb** [kamikat/bilibili-get#8]
Hello,

Thank you for this tool. However I can't get it to work, I have this error: 

> bilibili-get https://www.bilibili.com/video/av24796361
> extracting video metadata...
> [1/1] av24796361: start download "热干面大赛的冠军，带我去吃了另外一家热干面！ FINAL"...
> [1/1] av24796361: video quality:
> [1/1] av24796361:     112     hdflv2         高清 1080P+
> [1/1] av24796361:     80      flv            高清 1080P
> [1/1] av24796361:     64      flv720         高清 720P
> [1/1] av24796361:   * 32      flv480         清晰 480P
> [1/1] av24796361:     15      flv360         流畅 360P
> [1/1] av24796361: output format: flv
> [1/1] av24796361: output path:
> [1/1] av24796361:     /home/arnauld/Desktop/av24796361 热干面大赛的冠军，带我去吃了另外一家热干面！(1) FINAL.flv
> [1/1] av24796361: downloading video segment 1/2...
> Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--download-result'.
>   -> [OptionHandlerImpl.cc:444] errorCode=1 download-result must be one of the following:'default' 'full' 
> Usage:
>  --download-result=OPT        This option changes the way "Download Results"
>                               is formatted. If OPT is 'default', print GID,
>                               status, average download speed and path/URI. If
>                               multiple files are involved, path/URI of first
>                               requested file is printed and remaining ones are
>                               omitted.
>                               If OPT is 'full', print GID, status, average
>                               download speed, percentage of progress and
>                               path/URI. The percentage of progress and
>                               path/URI are printed for each requested file in
>                               each row.
> 
>                               Possible Values: default, full
>                               Default: default
>                               Tags: #advanced
> ERROR: download command failed with code 28.

**Comment by kamikat** [comment]
FYI https://github.com/kamikat/bilibili-get/issues/3#issuecomment-384827822

**Comment by arnauldb** [comment]
Ok, thank you.
